name: Build all subject PDFs

# Feel free to increment this counter in your attempts to do things
# the smart way instead of the easy way.
#
# total_hours_wasted = 7

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master

jobs:
  # vypis všech složek předmětů
  listDirectories: 
    runs-on: ubuntu-latest
    
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} # generate output name dir by using inner step output
    
    steps:
      # naklonování repa
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Prepare list of directories for jobs
        id: set-dirs # name for output 
        
        # vypis všech dir | odstranění template/ dir | odstranění prázdného řádku po template/dir
        # | odstranění všech speciálních znaků | rozdělení na json data pro matrix build
        run: echo "::set-output name=dir::$(ls -d */ | sed "s/template\///" | sed "/^$/d" |
         tr -dc '[:alnum:]\n\r-' | jq -R -s -c 'split("\n")[:-1]')"
  
  # build všech předmětů 
  subjects:
    runs-on: ubuntu-latest
    needs: listDirectories

    # vytvoření jobu pro každý předmět
    strategy:
      matrix:
        dir: ${{ fromJson(needs.listDirectories.outputs.dir) }} 

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      # kompilace
      - name: Build ${{ matrix.dir }}
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          working_directory: ${{ matrix.dir }}
          root_file: main.tex

      # nahrání pro pozdější stáhnutí
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.dir }} # název zip souboru se specifickým jméne předmětu
          path: ${{ matrix.dir }}/main.pdf # co se má uložit do zip souboru

  